### ISSUE TITLE
Support multiple choices

### ISSUE THREAD

**Issue by adrienbrault** [ArnaudRinquin/react-native-radio-buttons#22]

**Comment by ArnaudRinquin** [comment]
It seems like a good idea but goes against the initial goal of this component: the `radio` input behaviour (a.k.a single option select).

Also, this would require the following changes:
- [ ] Add the `maxSelectedOptions`, has a number property, defaulting to `1`.
- [ ] Add a `selectedOptions`,  has an Array property, defaulting to `[]`.
- [ ] Deprecate `selectedOption` property
- [ ] Change `onSelection` property function signature to receive an Array of selected options, instead of a single selected option.

These changes are breaking current API, which isn't really an issue.

Given the simplicity of such a multi-select list component, I feel like it should be implemented as another - independent - component, instead of a making `radio-buttons` a one-do-all component.

**Comment by ArnaudRinquin** [comment]
I'm closing the issue for now, I you want to discuss more about it please do.

**Comment by nzmedet** [comment]
> making radio-buttons a one-do-all component.

It's not one do all, it's form element, which has selection option, but awkward having it without multiple selection

README ambiguously says:

> A react component to implement radio buttons-like behaviors: **multiple options**, only one option can be selected at a given time.

Which is not clear at first glance

**Comment by PManager1** [comment]
@adrienbrault   
![image](https://user-images.githubusercontent.com/1026325/32741240-839fc498-c873-11e7-9b13-50870aba8069.png)

How about you can create multiple seperate components, so it will work like multiple options.

**Comment by Donhv** [comment]
@ArnaudRinquin How to multi select?

**Comment by ArnaudRinquin** [comment]
This package does not handle multi-selects.
